2024-07-27T08:44:23 {"cpu": 0.23828125, "cpu_total": 2, "cpu_usage": 0.119140625, "memory": 3623.0, "memory_total": 7938.0, "memory_usage": 0.4564121945074326, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069863.783788, "uuid": "6612ced24ddf416baea62327164d5302"}
2024-07-27T08:44:23 {"cpu": 0.23828125, "cpu_total": 2, "cpu_usage": 0.119140625, "memory": 3627.0, "memory_total": 7938.0, "memory_usage": 0.45691609977324266, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069863.889143, "uuid": "cf6e6892ffc24eeebc00f49574510fbd"}
2024-07-27T08:44:23 {"block_run_id": 1, "block_uuid": "load_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 1: pipeline doordash_eta block load_data", "timestamp": 1722069863.94635, "uuid": "706c512413d949bcadce27412e734ba3"}
2024-07-27T08:44:24 {"block_run_id": 1, "block_uuid": "load_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "BlockRun 1 (block_uuid: load_data) completes.", "timestamp": 1722069864.922359, "uuid": "59c823af489c4f3eb26506359373be68"}
2024-07-27T08:44:33 {"cpu": 0.2353515625, "cpu_total": 2, "cpu_usage": 0.11767578125, "memory": 3657.0, "memory_total": 7938.0, "memory_usage": 0.46069538926681786, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069873.955221, "uuid": "4f5c62c712d045e1b08008fa4ada63fb"}
2024-07-27T08:44:34 {"block_run_id": 2, "block_uuid": "clean_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 2: pipeline doordash_eta block clean_data", "timestamp": 1722069874.126177, "uuid": "5e36f0b83fa04bad95e91d64160e6900"}
2024-07-27T08:44:35 {"block_run_id": 2, "block_uuid": "clean_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "BlockRun 2 (block_uuid: clean_data) completes.", "timestamp": 1722069875.016661, "uuid": "52fcd9f4b753433a9aa73f1e9c5d40b3"}
2024-07-27T08:44:43 {"cpu": 0.232421875, "cpu_total": 2, "cpu_usage": 0.1162109375, "memory": 3610.0, "memory_total": 7938.0, "memory_usage": 0.45477450239355, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069883.048574, "uuid": "4dfd6864bdce472b8bca501f35904324"}
2024-07-27T08:44:43 {"block_run_id": 3, "block_uuid": "add_target_to_df", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 3: pipeline doordash_eta block add_target_to_df", "timestamp": 1722069883.158995, "uuid": "8cb3d6c6fe8f4cafbf0cad70923d53e9"}
2024-07-27T08:44:43 {"block_run_id": 5, "block_uuid": "make_fake_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 5: pipeline doordash_eta block make_fake_data", "timestamp": 1722069883.185666, "uuid": "d33c439327a843d88a6aad60b3319af3"}
2024-07-27T08:44:43 {"block_run_id": 3, "block_uuid": "add_target_to_df", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "BlockRun 3 (block_uuid: add_target_to_df) completes.", "timestamp": 1722069883.840609, "uuid": "66140596d4014a7b9a0a395eec69c831"}
2024-07-27T08:44:47 {"block_run_id": 5, "block_uuid": "make_fake_data", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "BlockRun 5 (block_uuid: make_fake_data) completes.", "timestamp": 1722069887.684926, "uuid": "798a670900e744a7900133bb74b174f6"}
2024-07-27T08:44:53 {"cpu": 0.2412109375, "cpu_total": 2, "cpu_usage": 0.12060546875, "memory": 3621.0, "memory_total": 7938.0, "memory_usage": 0.4561602418745276, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069893.134955, "uuid": "7dd257c401494f549d13f06eab8ab9b3"}
2024-07-27T08:45:03 {"cpu": 0.23828125, "cpu_total": 2, "cpu_usage": 0.119140625, "memory": 3731.0, "memory_total": 7938.0, "memory_usage": 0.47001763668430335, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069903.26009, "uuid": "8ec685ae400a4bb09925cec739f1b087"}
2024-07-27T08:45:03 {"block_run_id": 4, "block_uuid": "get_prediction", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 4: pipeline doordash_eta block get_prediction", "timestamp": 1722069903.453702, "uuid": "48dfd8a3a8db4fe5b418212cd88569cb"}
2024-07-27T08:45:03 {"block_run_id": 7, "block_uuid": "evidently_report", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Execute PipelineRun 1, BlockRun 7: pipeline doordash_eta block evidently_report", "timestamp": 1722069903.503559, "uuid": "30622b55c67243669ece2a7099a5b744"}
2024-07-27T08:45:04 {"block_run_id": 4, "block_uuid": "get_prediction", "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "EXCEPTION", "message": "BlockRun 4 (block_uuid: get_prediction) failed.", "timestamp": 1722069904.840059, "uuid": "875dc9c92e924e0ab982cda94740549e", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1673, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1650, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1552, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1892, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2023, in _execute_block\n    exec(self.content, results)\n  File \"<string>\", line 20, in <module>\n  File \"/usr/local/lib/python3.10/os.py\", line 680, in __getitem__\n    raise KeyError(key) from None\nKeyError: 'AWS_ACCESS_KEY_ID'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 147, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 787, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 106, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 58, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1735, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 334, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 641, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 20, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1232, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 465, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'AWS_ACCESS_KEY_ID'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1673, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1650, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1552, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1892, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2023, in _execute_block
    exec(self.content, results)
  File "<string>", line 20, in <module>
  File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'AWS_ACCESS_KEY_ID'
2024-07-27T08:45:13 {"cpu": 0.2470703125, "cpu_total": 2, "cpu_usage": 0.12353515625, "memory": 4610.0, "memory_total": 7938.0, "memory_usage": 0.580750818846057, "pipeline_run_id": 1, "pipeline_schedule_id": 2, "pipeline_uuid": "doordash_eta", "hostname": "2b37ed5d1a4e", "level": "INFO", "message": "Pipeline doordash_eta for run 1 in schedule 2 is alive.", "timestamp": 1722069913.388089, "uuid": "9f3cd33868c2460db1730a9783d8768d"}
